feat: actor_school_blacklist table
Mission-Prerna/nl-apis pull request #254
Opened 2024-07-01 07:25 UTC by Ajay-Maury

actor_school_blacklist table  created

2024-07-01 07:55 UTC, tushar5526 commented on prisma/schema.prisma
> +  actor_school_blacklist                       actor_school_blacklist[]
why this ?

2024-07-01 07:56 UTC, tushar5526 commented on prisma/schema.prisma
> +  actor_school_blacklist                   actor_school_blacklist[]
why we have this ?

2024-07-01 11:24 UTC, Ajay-Maury commented on prisma/schema.prisma
> +  actor_school_blacklist                   actor_school_blacklist[]
foreign key mappings

2024-07-02 06:45 UTC, tushar5526 commented on prisma/schema.prisma
> +  updated_at  DateTime    @default(now()) @db.Timestamptz(6)
Updated at should be configure as follows - https://github.com/prisma/prisma/discussions/20323

2024-07-02 06:48 UTC, tushar5526 commented on src/admin/admin.controller.ts
> +  async createSchoolActorBlacklist(
There should be a DELETE endpoint here as well.

2024-07-02 06:48 UTC, tushar5526 commented on src/admin/admin.controller.ts
> +  async createSchoolActorBlacklist(
Also add in the new endpoints in the NL APIs postman collection.

2024-07-02 06:49 UTC, tushar5526 requested changes
Please look at the comments.

2024-07-03 12:35 UTC, tushar5526 approved these changes

2024-07-03 12:43 UTC, merged