[#51] Localization of strings for various screens supported
Mission-Prerna/nl-apis pull request #52
Opened 2023-09-22 06:50 UTC by choxx

Refer #51 for more details

2023-09-22 07:29 UTC, yuvrajsab requested changes

2023-09-22 07:29 UTC, yuvrajsab commented on src/school/school.service.ts
> +    // @ts-ignore
why have you used `@ts-ignore` here? it is not a good practice, could have explicitly typed it `any` but in an ideal case, it should be correctly typed.

2023-09-22 07:54 UTC, choxx commented on src/school/school.service.ts
> +    // @ts-ignore
Fixed

2023-09-25 12:54 UTC, yuvrajsab approved these changes
lgtm.

2023-09-25 12:54 UTC, merged