fix: handle edge case when month == 12
Mission-Prerna/nl-apis pull request #92
Opened 2023-12-05 07:40 UTC by tushar5526

Related to #91

2023-12-05 07:47 UTC, karntrehan requested changes
Lets add test cases for the change. There are edge cases we could miss.

2023-12-05 08:03 UTC, chinmoy12c commented on src/school/school.service.v2.ts
> +          .replace('%end_time%', (moment().month(item.month + 1).year(item.year + (item.month + 1 == 12 ? 1 : 0)).date(1).startOf('day').format('YYYY-MM-DD HH:mm:ss')))
Why does `month + 1 == 12` add 1? Wouldn't that make the last month of the same year?? Can we have a single line of comment to explain these [MAGIC NUMBERS](https://en.wikipedia.org/wiki/Magic_number_(programming)#:~:text=In%20computer%20programming%2C%20a%20magic,see%20List%20of%20file%20signatures).

2023-12-05 08:52 UTC, ChakshuGautam requested changes

2023-12-05 08:52 UTC, ChakshuGautam commented on src/school/school.service.v2.ts
> +          .replace('%end_time%', (moment().month(item.month + 1).year(item.year + (item.month + 1 == 12 ? 1 : 0)).date(1).startOf('day').format('YYYY-MM-DD HH:mm:ss')))
Also consider replacing this to `DateTime` class with methods for formatting. Not able to make sense of what is happening and the kind of format that this is coverting it too. Also makes it difficutlt to write unit tests for this right now.

2023-12-05 09:47 UTC, tushar5526 commented on src/school/school.service.v2.ts
> +          .replace('%end_time%', (moment().month(item.month + 1).year(item.year + (item.month + 1 == 12 ? 1 : 0)).date(1).startOf('day').format('YYYY-MM-DD HH:mm:ss')))
`moment` is used across the whole codeabse at a lot of places, will make a separate ticket to switch to Datetime.

2023-12-05 09:47 UTC, tushar5526 commented on src/school/school.service.v2.ts
> +          .replace('%end_time%', (moment().month(item.month + 1).year(item.year + (item.month + 1 == 12 ? 1 : 0)).date(1).startOf('day').format('YYYY-MM-DD HH:mm:ss')))
> Why does `month + 1 == 12` add 1? Wouldn't that make the last month of the same year?? Can we have a single line of comment to explain these [MAGIC NUMBERS](https://en.wikipedia.org/wiki/Magic_number_(programming)#:~:text=In%20computer%20programming%2C%20a%20magic,see%20List%20of%20file%20signatures).

Sure will add a comments, basically months are 0 indexed in `moment` library.

2023-12-05 10:53 UTC, tushar5526 commented
hey @karntrehan @ChakshuGautam, adding tests to NL would require a bigger PR and a refactoring of modules. As of now, I have switched to using the `moment.js`'s `add` function to add months which will take care of edge cases.

2023-12-06 06:14 UTC, karntrehan approved these changes

2023-12-06 08:47 UTC, merged